root: true
parserOptions:
  ecmaVersion: 8
env:
  es6: true
  node: true
plugins:
  - prettier
extends:
  - eslint:recommended
  - plugin:prettier/recommended

overrides:
  - files: __tests__/**/*.js
    env:
      jest: true
